package br.rede.autoclustering.core;

public enum Parameter {
		
		ALL_DISTANCE,
		ALL_INSTANCES,
		ALL_GROUPS,
		ALL_LOWER_BOUNDS, 
		ALL_UPPER_BOUNDS,
	
		AMR_DENSITY,
		AMR_LAMBDA,
		AMR_SLICES,
		AMR_TREE,

		CLIQUE_SLICES,
		CLIQUE_SUBSPACES_BEGIN,
		CLIQUE_THRESHOLD,
		
		DBCLASD_PTS, 
		DBCLASD_GROUPS_FIRST,

		DBSCAN_NUM_PTS,
		DBSCAN_MAX_DIST,
		DBSCAN_GROUPS_FIRST,

		DESCRY_DENSITY,
		DESCRY_K,
		DESCRY_TREE,
		
		DHC_ATTRACTION_TREE,
		DHC_LIST_INSTANCE,
		DHC_MINPTS,
		DHC_SIGMA,
		DHC_THRESHOLD,

		DENCLUE_EPSILON,
		DENCLUE_HYPER_SPACE, 
		DENCLUE_SIGMA,
		
		PHC_GRID, PHC_RADIUS,PHC_GRID2,
		
		K_THRESHOLD,
		SNN_NUM_PTS,
		SNN_MAX_DIST,
		SNN_SN_Matrix,
		SNN_DENSITY,
		SNN_GROUPS_FIRST,
		
		DISTANCE_INFO,
		DISTANCE_MATRIX,
		DPCI_DC_PERCENT,
		DPCI_UPPERBOUND,
		DPCI_NORM_RHO,
		DPCI_NORM_DELTA,
		DPCI_ORD_RHO,
		DPCI_NEAREST_NEIGHBOR,

}
